// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuSjW33L7eSIclwW3OnjSFpoS3FQyDHyQ',
    appId: '1:200141120844:web:4f2f98b95068d6a278dbe9',
    messagingSenderId: '200141120844',
    projectId: 'gestao-producao-chopp',
    authDomain: 'gestao-producao-chopp.firebaseapp.com',
    storageBucket: 'gestao-producao-chopp.firebasestorage.app',
    measurementId: 'G-XEYKZBMGE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4hUyeAm37nq6ISi4Ou4OWbZXyOshsx8',
    appId: '1:200141120844:android:174c6038487799b878dbe9',
    messagingSenderId: '200141120844',
    projectId: 'gestao-producao-chopp',
    storageBucket: 'gestao-producao-chopp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdh5v1-Miv04LjDiEQIaLBjNDPTsXRhI',
    appId: '1:200141120844:ios:c177a7b06b86679278dbe9',
    messagingSenderId: '200141120844',
    projectId: 'gestao-producao-chopp',
    storageBucket: 'gestao-producao-chopp.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.gestaoProducaoChopp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdh5v1-Miv04LjDiEQIaLBjNDPTsXRhI',
    appId: '1:200141120844:ios:c177a7b06b86679278dbe9',
    messagingSenderId: '200141120844',
    projectId: 'gestao-producao-chopp',
    storageBucket: 'gestao-producao-chopp.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.gestaoProducaoChopp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuSjW33L7eSIclwW3OnjSFpoS3FQyDHyQ',
    appId: '1:200141120844:web:9476153b27b55a4778dbe9',
    messagingSenderId: '200141120844',
    projectId: 'gestao-producao-chopp',
    authDomain: 'gestao-producao-chopp.firebaseapp.com',
    storageBucket: 'gestao-producao-chopp.firebasestorage.app',
    measurementId: 'G-80ER482DNY',
  );
}
